### ISSUE TITLE
Hey Aditya 👋

### ISSUE THREAD

**Issue by rudrakshkarpe** [AdityaKane2001/AdityaKane2001#1]
I want to get started with ```TensorFlow```, I'm familiar with Python programming language and Learning ML fundamentals from Coursera.

What'd you recommend to get me started with Tenseflow and success in the long run! 
I hope you'll take some time to give a comprehensive roadmap from your experience in this domain that will eventually help me not to get lost in this field wandering for the best resources.

**Comment by AdityaKane2001** [comment]
Hi @rudrakshkarpe 

I recommend to start by going through this [course on Coursera](https://www.coursera.org/professional-certificates/tensorflow-in-practice). You might find similar videos on YouTube as well. 

Try to do a small personal project to understand the fundamentals. After that, start competing in Kaggle competitions to hone your skills.  TensorFlow docs are very well-written, so it is advisable to refer to them as frequently as needed. 

Hope I've answered your question!

**Comment by rudrakshkarpe** [comment]
Yes, definitely thanks for providing insights. I am looking forward to developing skills in Tensorflow and hoping for collaborations from you :)
